// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Oath")>]
[<assembly: AssemblyProductAttribute("Oath")>]
[<assembly: AssemblyDescriptionAttribute("Unit test XSLT with F#.")>]
[<assembly: AssemblyVersionAttribute("0.1.0")>]
[<assembly: AssemblyFileVersionAttribute("0.1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Oath"
    let [<Literal>] AssemblyProduct = "Oath"
    let [<Literal>] AssemblyDescription = "Unit test XSLT with F#."
    let [<Literal>] AssemblyVersion = "0.1.0"
    let [<Literal>] AssemblyFileVersion = "0.1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
